remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Wiki BotC FR"
description: "Traductions ğŸ‡«ğŸ‡· - Conseils et Ressources pour le jeu Blood ğŸ©¸on the Clocktower ğŸ•°ï¸"
url: "https://bambipotato.github.io/botc-fr-bambi/"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# fichiers supplÃ©mentaires Ã  inclure dans la compilation
include:
  - assets/css/style.css
  - assets/js/theme.js
  - _includes/head-custom.html
