remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Wiki BotC FR"
description: "Traductions, conseils et ressources pour Blood on the Clocktower"
url: "https://bambipotato.github.io/botc-fr-bambi/"
# Activer CSS et JS personnalis√©s
include:
  - assets/css/style.css
  - assets/js/theme.js
